// This file was generated by the Storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokRichTextDoc, StoryblokMultilink, StoryblokAsset } from '../storyblok.d.ts';
export interface Article {
  title?: string;
  slug?: string;
  excert?: string;
  featured_image?: StoryblokAsset;
  published_at?: string;
  body?: StoryblokRichTextDoc;
  author?: (ISbStoryData<Person> | string)[];
  seo?: UtilitySeo[];
  component: "article";
  _uid: string;
  _editable?: string | undefined;
}

export interface GlobalContactInfo {
  items?: ItemContactMethod[];
  component: "global_contact_info";
  _uid: string;
  _editable?: string | undefined;
}

export interface GlobalHeader {
  component: "global_header";
  _uid: string;
  _editable?: string | undefined;
}

export interface GlobalSocialLinks {
  items?: ItemSocialLink[];
  component: "global_social_links";
  _uid: string;
  _editable?: string | undefined;
}

export interface ItemAction {
  label: string;
  link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  style: "Primary" | "Secondary" | "Outline" | "Ghost" | "Text";
  component: "item_action";
  _uid: string;
  _editable?: string | undefined;
}

export interface ItemCard {
  eyebrow?: string;
  heading: string;
  body?: string;
  media?: StoryblokAsset;
  action?: ItemAction[];
  featured?: boolean;
  component: "item_card";
  _uid: string;
  _editable?: string | undefined;
}

export interface ItemContactMethod {
  type: "Email" | "Phone" | "Address" | "Business Hours" | "Website" | "Other";
  label?: string;
  value: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "item_contact_method";
  _uid: string;
  _editable?: string | undefined;
}

export interface ItemFaq {
  question: string;
  answer: StoryblokRichTextDoc;
  component: "item_faq";
  _uid: string;
  _editable?: string | undefined;
}

export interface ItemFeature {
  icon?: StoryblokAsset;
  heading: string;
  body?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "item_feature";
  _uid: string;
  _editable?: string | undefined;
}

export interface ItemGalleryImage {
  internal_name?: string;
  image: StoryblokAsset;
  caption?: string;
  credit?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "item_gallery_image";
  _uid: string;
  _editable?: string | undefined;
}

export interface ItemLogo {
  name: string;
  image: StoryblokAsset;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "item_logo";
  _uid: string;
  _editable?: string | undefined;
}

export interface ItemNavigationLink {
  label: string;
  link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  open_in_new_tab?: boolean;
  component: "item_navigation_link";
  _uid: string;
  _editable?: string | undefined;
}

export interface ItemProcessStep {
  internal_name?: string;
  eyebrow?: string;
  heading: string;
  body?: string;
  media?: StoryblokAsset;
  action?: ItemAction[];
  component: "item_process_step";
  _uid: string;
  _editable?: string | undefined;
}

export interface ItemResource {
  internal_name?: string;
  eyebrow?: string;
  title?: string;
  description?: string;
  resource_type?: number | string;
  link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  thumbnail?: StoryblokAsset;
  component: "item_resource";
  _uid: string;
  _editable?: string | undefined;
}

export interface ItemSocialLink {
  platform: number | string;
  label: string;
  link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "item_social_link";
  _uid: string;
  _editable?: string | undefined;
}

export interface ItemStat {
  prefix?: string;
  value: string;
  suffix?: string;
  label: string;
  description?: string;
  component: "item_stat";
  _uid: string;
  _editable?: string | undefined;
}

export interface ItemTestimonial {
  quote: string;
  name: string;
  role?: string;
  organization?: string;
  portrait?: StoryblokAsset;
  component: "item_testimonial";
  _uid: string;
  _editable?: string | undefined;
}

export interface ItemTimelineEvent {
  internal_name?: string;
  date?: string;
  date_label?: string;
  heading: string;
  body?: string;
  media?: StoryblokAsset;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "item_timeline_event";
  _uid: string;
  _editable?: string | undefined;
}

export interface Navigation {
  internal_name?: string;
  items?: (NavigationItem | ItemNavigationLink)[];
  component: "navigation";
  _uid: string;
  _editable?: string | undefined;
}

export interface Page {
  internal_name?: string;
  title?: string;
  body?: (
    | Article
    | GlobalContactInfo
    | GlobalHeader
    | GlobalSocialLinks
    | ItemAction
    | ItemCard
    | ItemContactMethod
    | ItemFaq
    | ItemFeature
    | ItemGalleryImage
    | ItemLogo
    | ItemNavigationLink
    | ItemProcessStep
    | ItemResource
    | ItemSocialLink
    | ItemStat
    | ItemTestimonial
    | ItemTimelineEvent
    | Navigation
    | Page
    | Person
    | SectionAnnouncement
    | SectionCardGrid
    | SectionFaq
    | SectionFeatureList
    | SectionGallery
    | SectionHero
    | SectionPageIntro
    | SectionProcess
    | SectionRichText
    | SectionSplitContent
    | SectionStats
    | SectionTeam
    | SectionTestimonials
    | SectionTimeline
    | Service
    | SiteSettings
    | UtilitySeo
  )[];
  seo?: UtilitySeo[];
  hide_from_navigation?: boolean;
  component: "page";
  _uid: string;
  _editable?: string | undefined;
}

export interface Person {
  name?: string;
  headshot?: StoryblokAsset;
  short_bio?: string;
  full_bio?: string;
  email?: string;
  phone?: string;
  social_links?: ItemSocialLink[];
  component: "person";
  _uid: string;
  _editable?: string | undefined;
}

export interface SectionAnnouncement {
  message: string;
  action?: ItemAction[];
  dismissible?: boolean;
  theme?: number | string;
  component: "section_announcement";
  _uid: string;
  _editable?: string | undefined;
}

export interface SectionCardGrid {
  eyebrow?: string;
  heading: string;
  body?: string;
  cards?: ItemCard[];
  columns?: "" | "One" | "Two" | "Three" | "Four";
  theme?: number | string;
  component: "section_card_grid";
  _uid: string;
  _editable?: string | undefined;
}

export interface SectionFaq {
  heading: string;
  body?: string;
  items?: (ItemFeature | ItemFaq)[];
  allow_multiple_open?: boolean;
  theme?: number | string;
  component: "section_faq";
  _uid: string;
  _editable?: string | undefined;
}

export interface SectionFeatureList {
  eyebrow?: string;
  heading: string;
  body?: string;
  features?: ItemFeature[];
  columns?: string;
  theme?: number | string;
  component: "section_feature_list";
  _uid: string;
  _editable?: string | undefined;
}

export interface SectionGallery {
  heading: string;
  body?: string;
  images?: ItemGalleryImage[];
  allow_lightbox?: boolean;
  theme?: number | string;
  component: "section_gallery";
  _uid: string;
  _editable?: string | undefined;
}

export interface SectionHero {
  internal_name?: string;
  eyebrow?: string;
  heading: string;
  body?: StoryblokRichTextDoc;
  media?: StoryblokAsset;
  actions?: ItemAction[];
  theme: number | string;
  layout: "Centered" | "Media Right" | "Media Left";
  text_alignment: "Left" | "Center" | "Right";
  component: "section_hero";
  _uid: string;
  _editable?: string | undefined;
}

export interface SectionPageIntro {
  eyebrow?: string;
  heading: string;
  body?: StoryblokRichTextDoc;
  theme?: number | string;
  alignment: "Left" | "Center" | "Right";
  component: "section_page_intro";
  _uid: string;
  _editable?: string | undefined;
}

export interface SectionProcess {
  eyebrow?: string;
  heading: string;
  body?: string;
  steps?: ItemProcessStep[];
  theme?: number | string;
  component: "section_process";
  _uid: string;
  _editable?: string | undefined;
}

export interface SectionRichText {
  heading: string;
  content?: StoryblokRichTextDoc;
  width?: number | string;
  alignment: "Left" | "Center" | "Right";
  theme?: number | string;
  component: "section_rich_text";
  _uid: string;
  _editable?: string | undefined;
}

export interface SectionSplitContent {
  eyebrow?: string;
  heading: string;
  body?: StoryblokRichTextDoc;
  media: StoryblokAsset;
  actions?: ItemAction[];
  media_position?: "" | "Left" | "Right";
  media_style?: number | string;
  theme?: number | string;
  component: "section_split_content";
  _uid: string;
  _editable?: string | undefined;
}

export interface SectionStats {
  heading: string;
  body?: string;
  stats?: ItemStat[];
  theme?: number | string;
  component: "section_stats";
  _uid: string;
  _editable?: string | undefined;
}

export interface SectionTeam {
  heading: string;
  body?: string;
  people?: (ISbStoryData<Person> | string)[];
  show_bios?: boolean;
  theme?: number | string;
  component: "section_team";
  _uid: string;
  _editable?: string | undefined;
}

export interface SectionTestimonials {
  heading: string;
  body?: string;
  testimonials?: ItemTestimonial[];
  theme?: number | string;
  component: "section_testimonials";
  _uid: string;
  _editable?: string | undefined;
}

export interface SectionTimeline {
  heading: string;
  body?: string;
  events?: ItemTimelineEvent[];
  theme?: number | string;
  component: "section_timeline";
  _uid: string;
  _editable?: string | undefined;
}

export interface Service {
  name?: string;
  description?: string;
  icon?: StoryblokAsset;
  featured_image?: StoryblokAsset;
  body?: StoryblokRichTextDoc;
  seo?: UtilitySeo[];
  component: "service";
  _uid: string;
  _editable?: string | undefined;
}

export interface SiteSettings {
  site_name?: string;
  site_description?: string;
  logo?: StoryblokAsset;
  logo_dark?: StoryblokAsset;
  favicon?: StoryblokAsset;
  default_social_image?: StoryblokAsset;
  component: "site_settings";
  _uid: string;
  _editable?: string | undefined;
}

export interface UtilitySeo {
  title?: string;
  description?: string;
  social_title?: string;
  social_image?: StoryblokAsset;
  canonical_url?: string;
  component: "utility_seo";
  _uid: string;
  _editable?: string | undefined;
}

export type ContentType = Article | Navigation | Page | Person | Service | SiteSettings;
